### ISSUE TITLE
please add support to custom gas token

### ISSUE THREAD

**Issue by JustPandaEver** [rabbitprincess/builderism#12]
https://docs.optimism.io/builders/chain-operators/features/custom-gas-token
:)

**Comment by rabbitprincess** [comment]
https://www.notion.so/oplabs/EXTERNAL-How-to-run-a-Custom-Gas-Token-chain-d88c68306f934790be051f87213a0b1d

**Comment by rabbitprincess** [comment]
https://github.com/rabbitprincess/builderism/tree/feature/custom-gas-token
